# Generated by Django 5.2.2 on 2025-06-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_app', '0002_comment_delete_cultureevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
