# Generated by Django 5.2.2 on 2025-06-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_app', '0003_alter_comment_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
